---
- name: Install Java 1.8 and Tomca8
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
  - openjdk-8-jdk
  - tomcat8
  - maven
  tags:
    - tomcat8

- name: copy maven settings
  copy: src=maven.sh dest=/etc/profile.d owner=root group=root mode=0644

- name: Configure Tomcat server
  template: src=server.xml dest=/var/lib/tomcat8/conf/
  notify: Restart tomcat

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/var/lib/tomcat8/conf/
  notify: Restart tomcat

- name: Start Tomcat
  service: name=tomcat8 state=started enabled=yes
  tags: [service,tomcat]

- name: wait for tomcat to start
  wait_for: port={{central_http_port}}
