language: python
python: '2.7'
sudo: false
addons:
  apt:
    packages:
    - python-pip
install:
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- ansible-playbook ansible/site.yml -i ansible/hosts -l tomcat-servers --syntax-check
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: QQBiN3fVPzpNOmUhszpcTLBdDRFS8hrcx13V6pbxAvx2nd79WYa4N8E4rH/nATnmNFI+W0pGzu7ImUXpnVRTTnIkIO8K/rmme6wHrAgYU5xCWceMprXp2oklxZNmiR3wSXn8mGUAJ4wirRQRkqitYni3pmFVS/rjh1E3ghpfTD0=
  email:
    on_success: never
