---
- name: Clean up the project
  command: /usr/bin/mvn clean
  args:
    chdir: /project/wf-central

- name: Building workflow project
  async: 1000
  poll: 0
  command: /usr/bin/mvn tomcat7:run-war -DskipTests
  args:
    chdir: /project/wf-central

- name: wait for tomcat to start
  wait_for: port={{central_http_port}}
