---
# This playbook deploys a simple standalone Tomcat 7 server. 

- hosts: tomcat-servers
  become: true
  become_user: root

  roles:
    - common
    - tomcat
    - wf-central-java
    - wf-region-java
