---
- name: Clean up the project
  command: /usr/bin/mvn clean
  args:
    chdir: /project/wf-region

- name: Build workflow project
  command: /usr/bin/mvn package -DskipTests
  args:
    chdir: /project/wf-region

- name: Deploy artifact to tomcat
  command: curl -s --upload-file /project/wf-region/target/wf-region.war "http://{{ tomcat_user }}:{{ tomcat_pass }}@127.0.0.1:{{ tomcat_port | default(8080) }}/manager/text/deploy?path=/wf-region&update=true"
  register: curl_output


- name: Fail playbook if deployment failed
  fail: msg="Deployment failed"
  when: "item.stdout is defined and 'FAIL' in item.stdout"
  with_items:
    - "{{ curl_output.results }}"
